### POST request to Create a new Entity
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "John Doe kafka test1",
  "email": "kafka_test1@yahoo.com",
  "address": "123 main street",
  "dateOfBirth": "1995-09-09",
  "registeredDate": "2024-11-28"
}

###