### Login Request to retrive a token
POST http://lb-520dbf86.elb.localhost.localstack.cloud:4004/auth/login
content-Type: application/json

{
  "email": "testuser@test.com",
  "password": "password123"
}

> {% client.global.set("token", response.body.token) %}